service: bearer-authentication
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs14.x
    memorySize: 128
    timeout: 30
    region: ap-northeast-1
    stage: ${opt:stage, self:custom.defaultStage}
    iam: ${file(./config/iam.yml)}
    deploymentBucket:
      name: bbbsquash-cloud.com
    stackTags:
      COMMIT_ID: ${file(../utils/git.js):getCommitId}

custom:
  defaultStage: prd

functions:
  handler:
    handler: index.handler
    name: ${sls:stage}-${self:service}
    environment: ${file(./config/environment.yml)}