version: '3.8'

services:
  front:
    container_name: front
    build: ./docker/front
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./server:/app:cached
    tty: true
    stdin_open: true
    command: /bin/sh
